FROM ubuntu:14.04

RUN apt-get update \
    && apt-get install -y wget git \
    && wget -q -O- https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add - \
    && echo 'deb http://download.fpcomplete.com/ubuntu trusty main' | sudo tee /etc/apt/sources.list.d/fpco.list \
    && apt-get update
RUN apt-get install -y --no-install-recommends \
    libsdl2-dev \
    libcairo2-dev \
    libpango1.0-de \
#    wget \
    libgles2-mesa-dev \
    gcc \
    git \
    libffi-dev \
    libgmp-dev \
    make \
    xz-utils \
#    && apt-get install libgles2-mesa-dev libsdl2-dev libghc-gtk-dev stack wget -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# install stack
RUN wget -qO- --no-check-certificate https://get.haskellstack.org/ | sh

WORKDIR /app/helmsnake
COPY stack.yaml .
COPY helmsnake.cabal .

RUN stack setup \
    && stack install gtk2hs-buildtools
RUN stack build --only-dependencies

COPY . .

RUN stack build
